# Generated by Django 2.0.6 on 2018-10-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_mainnav'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainnav',
            name='img',
            field=models.CharField(default=None, max_length=255, verbose_name='图片链接地址'),
        ),
        migrations.AddField(
            model_name='mainnav',
            name='name',
            field=models.CharField(default=None, max_length=64, verbose_name='图片名称'),
        ),
        migrations.AddField(
            model_name='mainnav',
            name='trackid',
            field=models.CharField(default='1', max_length=50, verbose_name='图片id'),
        ),
        migrations.AlterField(
            model_name='mainwheel',
            name='img',
            field=models.CharField(default=None, max_length=255, verbose_name='图片链接地址'),
        ),
        migrations.AlterField(
            model_name='mainwheel',
            name='name',
            field=models.CharField(default=None, max_length=64, verbose_name='图片名称'),
        ),
    ]
