# Generated by Django 2.0.6 on 2018-10-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20181029_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMustBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(default=None, max_length=255, verbose_name='图片链接地址')),
                ('name', models.CharField(default=None, max_length=64, verbose_name='图片名称')),
                ('trackid', models.CharField(default='1', max_length=50, verbose_name='图片id')),
            ],
            options={
                'verbose_name': '每日必买',
                'verbose_name_plural': '每日必买',
                'db_table': 'axf_mustbuy',
            },
        ),
    ]
