# Generated by Django 2.0.6 on 2018-10-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_mainshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(default=None, max_length=255, verbose_name='图片链接地址')),
                ('name', models.CharField(default=None, max_length=64, verbose_name='图片名称')),
                ('trackid', models.CharField(default='1', max_length=50, verbose_name='图片id')),
                ('categoryid', models.CharField(max_length=20, verbose_name='分类ID')),
                ('brandname', models.CharField(max_length=50, verbose_name='品牌名')),
                ('img1', models.CharField(max_length=255, verbose_name='图片1')),
                ('childcid1', models.CharField(max_length=20, verbose_name='商品1ID')),
                ('productid1', models.CharField(max_length=20, verbose_name='产品1编号')),
                ('longname1', models.CharField(max_length=20, verbose_name='商品1名称')),
                ('price1', models.FloatField(default=1, verbose_name='商品1价格')),
                ('marketprice1', models.FloatField(default=1, verbose_name='市场价')),
                ('img2', models.CharField(max_length=255, verbose_name='图片2')),
                ('childcid2', models.CharField(max_length=20, verbose_name='商品1ID')),
                ('productid2', models.CharField(max_length=20, verbose_name='产品2编号')),
                ('longname2', models.CharField(max_length=20, verbose_name='商品2名称')),
                ('price2', models.FloatField(default=1, verbose_name='商品2价格')),
                ('marketprice2', models.FloatField(default=1, verbose_name='市场价')),
                ('img3', models.CharField(max_length=255, verbose_name='图片3')),
                ('childcid3', models.CharField(max_length=20, verbose_name='商品3ID')),
                ('productid3', models.CharField(max_length=20, verbose_name='产品3编号')),
                ('longname3', models.CharField(max_length=20, verbose_name='商品3名称')),
                ('price3', models.FloatField(default=1, verbose_name='商品3价格')),
                ('marketprice3', models.FloatField(default=1, verbose_name='市场价')),
            ],
            options={
                'verbose_name': '商品展示',
                'verbose_name_plural': '商品展示',
                'db_table': 'axf_mainshow',
            },
        ),
    ]
