# Generated by Django 2.0.6 on 2018-10-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_mainshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainshow',
            name='longname1',
            field=models.CharField(max_length=100, verbose_name='商品1名称'),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='longname2',
            field=models.CharField(max_length=100, verbose_name='商品2名称'),
        ),
        migrations.AlterField(
            model_name='mainshow',
            name='longname3',
            field=models.CharField(max_length=100, verbose_name='商品3名称'),
        ),
    ]
