# Generated by Django 2.0.6 on 2018-10-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20181029_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFoodTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(default=1, verbose_name='产品类型ID')),
                ('typename', models.CharField(max_length=100, verbose_name='产品名称')),
                ('childtypenames', models.CharField(max_length=100, verbose_name='子类型名称')),
                ('typesort', models.IntegerField(default=1, verbose_name='类型顺序')),
            ],
            options={
                'verbose_name': '食品类型',
                'verbose_name_plural': '食品类型',
                'db_table': 'axf_foodtypes',
            },
        ),
    ]
