# Generated by Django 2.0.6 on 2018-10-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20181030_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='childidname',
            new_name='childcidname',
        ),
    ]
